In [50]:
import numpy as np 
import pandas as pd

In [51]:
df = pd.read_csv(r"C:\Users\ashis\Desktop\python\house_price_pre\Bengaluru_House_Data.csv")

In [52]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [53]:
df.drop(columns=["area_type","availability","society","balcony"], inplace=True)

In [54]:
# apply EDA and data cleaning steps here

In [55]:
df

                       location       size total_sqft  bath   price
0      Electronic City Phase II      2 BHK       1056   2.0   39.07
1              Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2                   Uttarahalli      3 BHK       1440   2.0   62.00
3            Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                      Kothanur      2 BHK       1200   2.0   51.00
...                         ...        ...        ...   ...     ...
13315                Whitefield  5 Bedroom       3453   4.0  231.00
13316             Richards Town      4 BHK       3600   5.0  400.00
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0   60.00
13318           Padmanabhanagar      4 BHK       4689   4.0  488.00
13319              Doddathoguru      1 BHK        550   1.0   17.00

[13320 rows x 5 columns]

In [56]:
df.shape

(13320, 5)

In [57]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [58]:
df.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [59]:
df["size"].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [60]:
df["location"].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [61]:
df["bath"].unique()

array([ 2.,  5.,  3.,  4.,  6.,  1.,  9., nan,  8.,  7., 11., 10., 14.,
       27., 12., 16., 40., 15., 13., 18.])

In [62]:
df["location"] =df["location"].fillna("Sarjapur Road")

In [63]:
df["size"] = df["size"].fillna("2 BHK")

In [64]:
df["bath"] = df["bath"].fillna(df["bath"].median())

In [65]:
df.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [66]:
df["BHK"] = df["size"].str.split().str.get(0).astype(int)

In [67]:
df[df.BHK>20]

                       location        size total_sqft  bath  price  BHK
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [68]:
df["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [69]:
def convert_sqft_to_num(x):
    try:
        tokens = x.split('-')
        if len(tokens) == 2:
            return (float(tokens[0]) + float(tokens[1])) / 2
        else:
            return float(x)
    except:
        return None

In [70]:
df["total_sqft"] = df["total_sqft"].apply(convert_sqft_to_num)

In [71]:
df.head()

                   location       size  total_sqft  bath   price  BHK
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [72]:
df["price_per_sqft"] = df["price"]*100000 / df["total_sqft"]

In [73]:
df.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [74]:
df["location"].value_counts()

location
Whitefield                                      540
Sarjapur  Road                                  399
Electronic City                                 302
Kanakpura Road                                  273
Thanisandra                                     234
                                               ...
Maragondana Halli, kr puram, old madras road      1
Chikkajala                                        1
Udayagiri                                         1
pavitra paradise                                  1
Chikbasavanapura                                  1
Name: count, Length: 1306, dtype: int64

In [75]:
df["location"] = df["location"].apply(lambda x: x.strip())
location_count = df["location"].value_counts( )

In [76]:
location_count

location
Whitefield                541
Sarjapur  Road            399
Electronic City           304
Kanakpura Road            273
Thanisandra               237
                         ...
Xavier Layout               1
Ramanagara Channapatna      1
Maheswari Nagar             1
Hsr layout sector3          1
Thyagraj Nagar              1
Name: count, Length: 1295, dtype: int64

In [77]:
location_count10 = location_count[location_count<=15]
location_count10

location
Kodihalli                 15
Benson Town               15
Nagavarapalya             15
Varthur Road              15
Chamrajpet                15
                          ..
Xavier Layout              1
Ramanagara Channapatna     1
Maheswari Nagar            1
Hsr layout sector3         1
Thyagraj Nagar             1
Name: count, Length: 1114, dtype: int64

In [78]:
df["location"] = df["location"].apply(lambda x: 'other' if x in location_count10 else x)

In [79]:
df["location"].value_counts()

location
other                    3647
Whitefield                541
Sarjapur  Road            399
Electronic City           304
Kanakpura Road            273
                         ...
Banashankari Stage VI      16
Cooke Town                 16
Banashankari Stage II      16
Judicial Layout            16
Sector 2 HSR Layout        16
Name: count, Length: 182, dtype: int64

In [80]:
df.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [81]:
(df["total_sqft"]/df["BHK"]).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [82]:
df = df[(df["total_sqft"]/df["BHK"])>=300]
df.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [83]:
df.shape

(12530, 7)

In [84]:
df.price_per_sqft.describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [85]:
# Remove outliers from price per sqft
def remove_pps_outliers(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby("location"):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        reduced_df = subdf[(subdf.price_per_sqft>(m-st)) & (subdf.price_per_sqft<=(m+st))]
        df_out = pd.concat([df_out,reduced_df],ignore_index=True)
    return df_out
df = remove_pps_outliers(df)
df.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  10417.000000  10417.000000  10417.000000  10417.000000    10417.000000
mean    1505.211858      2.472209     89.860367      2.575310     5616.562249
std      876.343788      0.981697     80.350452      0.902142     2145.778121
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1106.000000      2.000000     48.790000      2.000000     4237.185056
50%     1282.000000      2.000000     67.000000      2.000000     5166.666667
75%     1650.000000      3.000000    100.000000      3.000000     6410.256410
max    30400.000000     16.000000   2200.000000     16.000000    21875.000000

In [86]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby("location"):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby("BHK"):
            bhk_stats[bhk] = {
                "mean": np.mean(bhk_df.price_per_sqft),
                "std": np.std(bhk_df.price_per_sqft),
                "count": bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby("BHK"):
            stats = bhk_stats.get(bhk-1)
            if stats and stats["count"]>5:
                exclude_indices = np.append(exclude_indices,
                    bhk_df[bhk_df.price_per_sqft < (stats["mean"])].index.values)
    return df.drop(exclude_indices, axis="index")

In [87]:
df = bhk_outlier_remover(df)
df.describe()

         total_sqft         bath        price          BHK  price_per_sqft
count   7164.000000  7164.000000  7164.000000  7164.000000     7164.000000
mean    1494.505637     2.448772    98.683809     2.496092     6145.323865
std      859.858930     1.012293    87.464934     0.923795     2279.532662
min      300.000000     1.000000    10.000000     1.000000     1300.000000
25%     1098.000000     2.000000    50.660000     2.000000     4687.500000
50%     1260.000000     2.000000    75.000000     2.000000     5745.856354
75%     1680.500000     3.000000   115.000000     3.000000     6954.298995
max    30000.000000    16.000000  2200.000000    16.000000    21875.000000

In [88]:
df

,location,size,total_sqft,bath,price,BHK,price_per_sqft
1,1st Phase JP Nagar,3 BHK,1875.0,3.0,167.0,3,8906.666667
2,1st Phase JP Nagar,5 Bedroom,1500.0,5.0,85.0,5,5666.666667
3,1st Phase JP Nagar,3 BHK,2065.0,4.0,210.0,3,10169.491525
5,1st Phase JP Nagar,3 BHK,2059.0,3.0,225.0,3,10927.634774
6,1st Phase JP Nagar,2 BHK,1394.0,2.0,100.0,2,7173.601148
...,...,...,...,...,...,...,...
10404,other,1 BHK,1800.0,1.0,200.0,1,11111.111111
10410,other,2 BHK,1353.0,2.0,110.0,2,8130.081301
10411,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443
10414,other,2 BHK,1200.0,2.0,140.0,2,11666.666667
10416,other,4 BHK,3600.0,5.0,400.0,4,11111.111111

In [89]:
df.drop(columns=["size","price_per_sqft"], inplace=True)

In [90]:
df

                 location  total_sqft  bath  price  BHK
1      1st Phase JP Nagar      1875.0   3.0  167.0    3
2      1st Phase JP Nagar      1500.0   5.0   85.0    5
3      1st Phase JP Nagar      2065.0   4.0  210.0    3
5      1st Phase JP Nagar      2059.0   3.0  225.0    3
6      1st Phase JP Nagar      1394.0   2.0  100.0    2
...                   ...         ...   ...    ...  ...
10404               other      1800.0   1.0  200.0    1
10410               other      1353.0   2.0  110.0    2
10411               other       812.0   1.0   26.0    1
10414               other      1200.0   2.0  140.0    2
10416               other      3600.0   5.0  400.0    4

[7164 rows x 5 columns]

In [91]:
X = df.drop(columns=["price"])
y = df["price"]

In [92]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression , Ridge, Lasso
from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [94]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(5731, 4) (1433, 4) (5731,) (1433,)

# apply the liner regression

In [95]:
column_transformer = make_column_transformer([
    ("ohe", OneHotEncoder(handle_unknown="ignore"), ["location"]),
    ("scaler", StandardScaler(), ["total_sqft", "bathrooms", "bedrooms"])
])

In [96]:
lr = LinearRegression()

In [97]:
pipeline = make_pipeline(column_transformer, lr)

In [98]:
pipeline.fit(X_train, y_train)

TypeError: All estimators should implement fit and transform, or can be 'drop' or 'passthrough' specifiers. '('ohe', OneHotEncoder(handle_unknown='ignore'), ['location'])' (type <class 'tuple'>) doesn't.

In [99]:
# fix ColumnTransformer (was created with nested tuples) and correct column names, then refit pipeline
column_transformer = make_column_transformer(
    (OneHotEncoder(handle_unknown="ignore"), ["location"]),
    (StandardScaler(), ["total_sqft", "bath", "BHK"]),
    remainder="passthrough"
)

pipeline = make_pipeline(column_transformer, lr)
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

# quick evaluation
print("Train R2:", r2_score(y_train, pipeline.predict(X_train)))
print("Test R2:", r2_score(y_test, pipeline.predict(X_test)))

Train R2: 0.8337921771728106
Test R2: 0.8910136675238383

# appling lasso

In [100]:
lasso = Lasso() 
pipeline = make_pipeline(column_transformer, lasso)
pipeline.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location']),
                                                 ('standardscaler',
                                                  StandardScaler(),
                                                  ['total_sqft', 'bath',
                                                   'BHK'])])),
                ('lasso', Lasso())])

In [101]:
y_pred_lasso = pipeline.predict(X_test)

In [102]:
print(r2_score(y_test, y_pred_lasso))

0.8366384002031267

In [103]:
r2_score(y_train, pipeline.predict(X_train))

0.7496490673378537

# Ridge

In [104]:
ridge = Ridge()
pipeline = make_pipeline(column_transformer, ridge)
pipeline.fit(X_train, y_train)
y_pred_ridge = pipeline.predict(X_test)
print(r2_score(y_test, y_pred_ridge))

0.8911757483607103

In [105]:
print("No regularization ",r2_score(y_test, y_pred))
print("Lasso regularization ",r2_score(y_test, y_pred_lasso))
print("Ridge regularization ",r2_score(y_test, y_pred_ridge))

No regularization  0.8910136675238383
Lasso regularization  0.8366384002031267
Ridge regularization  0.8911757483607103

In [ ]:
df['location'].value_counts()

np.int64(7164)

In [116]:
top_locations = df['location'].value_counts().head(20).index.tolist()
print(top_locations)

['other', 'Whitefield', 'Sarjapur  Road', 'Electronic City', 'Raja Rajeshwari Nagar', 'Uttarahalli', 'Haralur Road', 'Marathahalli', 'Bannerghatta Road', 'Hennur Road', 'Thanisandra', 'Hebbal', 'Kanakpura Road', 'Electronic City Phase II', 'Yelahanka', '7th Phase JP Nagar', 'Bellandur', 'KR Puram', 'Chandapura', 'Harlur']

In [107]:
import pickle

In [108]:
pickle.dump(pipeline, open("bangluru_house_price_model.pkl", "wb"))

In [109]:
pickle_model = pickle.load(open("bangluru_house_price_model.pkl", "rb"))
print(pickle_model.predict(X_test.head(5)))

[ 90.73629987   9.28339465 139.68500561  51.31772873 100.52753513]

In [110]:
pickle_model.predict(X_test.iloc[0:1])

array([90.73629987])